name: Test and Push Docker image

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - .github/**
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - .github/**
      - '.gitignore'
      - 'README.md'
  workflow_dispatch:
    inputs:
      image-test:
        type: boolean
        description: Run docker image tests
        required: false
      image-push:
        type: boolean
        description: Build and push image
        required: false

jobs:
  docker-test:
    name: Test docker image
    if: github.event.inputs.image-test == 'True' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t image-test .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'image-test'
          format: 'table'
          # exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  docker-push:
    name: Push docker image to Docker Hub
    if: github.event.inputs.image-push == 'True' || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract branch and tag
      run: |
        echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/dockertest:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/dockertest:${{ env.commit_hash }}